const $totalSaving = $("#totalSaving")
const $retry = $("#retry")
const $guestCount = $("#guestCount")
const $earn = $("#earn")
const $next = $("#next")
// const $time = $("#time")

const totalSaving = localStorage.getItem("totalSaving") 
const previous = localStorage.getItem("previous")
const next = localStorage.getItem("next")
const guestCount = localStorage.getItem("guestCount")
const earn = localStorage.getItem("earn")
// const time = localStorage.getItem("time")  

$totalSaving.text(totalSaving)
$retry.attr("href", previous)
$next.attr("href", next)
$guestCount.text(guestCount)
$earn.text(earn)
// $time.text(time)